### PR TITLE
Finished About, Contact, Sigin and signUp Sections

### PR DESCRIPTION
**Pull request by abdulahinor**
This project is a simple, responsive web page featuring sections such as About, Contact, and authentication forms (Sign In and Sign Up).

### CODE REVIEW

**Review by abdilahimohamet — CHANGES_REQUESTED** [review]
eng qaybta links ee headerka ku xidh sections sida home,about page

**Comment by abdulahinor** [comment]
eng ciladii links ee headerka ku xidh sections sida home,about page waa xaliyey

**Comment by abdilahimohamet** [comment]
eng waa kaa hayaa okey

**Review by abdilahimohamet — APPROVED** [review]
thanks sxb good

**Pull request merged**
